name: learn-github-actions
on: [push]
jobs:
  checkout-bats-version:
    runs-on: ubuntu-latest
    steps:
    - uses: github/checkout@v2
    - uses: action/setup-python@v1
    - uses: BSFishy/pip-action@v1
      with:
        requirements: requirements.txt
    - run: python test.py